export const reelsMock = [
  {
    id: 'reel-1',
    title: 'Погружение в вкус Азии',
    subtitle: 'Паназиатская кухня нового уровня',
    text: 'Приятного аппетита с азиатским акцентом',
    avatar: '/images/reels/reel.webp',
    preview: './images/reels/reel.webp',
    items: [{ src: './images/reels/reel.webp', duration: 1000 }],
  },
  {
    id: 'reel-2',
    title: 'Ваш азиатский гастрономический тур',
    subtitle: 'Собрали лучшие вкусы в одном меню',
    text: 'Открывайте новые сочетания каждый день',
    avatar: '/images/reels/reel.webp',
    preview: './images/reels/reel.webp',
    items: [
      { src: './images/reels/reel.webp', duration: 5000 },
      { src: './files/reels.webm', duration: 0 },
      { src: './images/reels/reel.webp', duration: 3500 },
    ],
  },
  {
    id: 'reel-3',
    title: 'Пицца, как в Неаполе',
    subtitle: 'Тесто 48 часов ферментации',
    text: 'Хрустящая корочка и сочная начинка',
    avatar: '/images/reels/reel.webp',
    preview: './images/reels/reel.webp',
    items: [
      { src: './files/reels.webm', duration: 0 },
      { src: './images/reels/reel.webp', duration: 5000 },
    ],
  },
  {
    id: 'reel-4',
    title: 'Рамен и лапша wok',
    subtitle: 'Глубокий бульон и яркие соусы',
    text: 'Горячо, насыщенно, ароматно',
    avatar: '/images/reels/reel.webp',
    preview: './images/reels/reel.webp',
    items: [
      { src: './images/reels/reel.webp', duration: 5000 },
      { src: './images/reels/reel.webp', duration: 5000 },
    ],
  },
  {
    id: 'reel-5',
    title: 'Димсам и закуски',
    subtitle: 'Идеально к вечерним встречам',
    text: 'Подача, которую хочется снять в сторис',
    avatar: '/images/reels/reel.webp',
    preview: './images/reels/reel.webp',
    items: [
      { src: './images/reels/reel.webp', duration: 4500 },
      { src: './files/reels.webm', duration: 0 },
      { src: './images/reels/reel.webp', duration: 4500 },
      { src: './images/reels/reel.webp', duration: 3500 },
    ],
  },
  {
    id: 'reel-6',
    title: 'Димсам и закуски',
    subtitle: 'Идеально к вечерним встречам',
    text: 'Подача, которую хочется снять в сторис',
    avatar: '/images/reels/reel.webp',
    preview: './images/reels/reel.webp',
    items: [
      { src: './images/reels/reel.webp', duration: 4500 },
      { src: './files/reels.webm', duration: 0 },
      { src: './images/reels/reel.webp', duration: 4500 },
      { src: './images/reels/reel.webp', duration: 3500 },
    ],
  },
  {
    id: 'reel-7',
    title: 'Димсам и закуски',
    subtitle: 'Идеально к вечерним встречам',
    text: 'Подача, которую хочется снять в сторис',
    avatar: '/images/reels/reel.webp',
    preview: './images/reels/reel.webp',
    items: [
      { src: './images/reels/reel.webp', duration: 4500 },
      { src: './files/reels.webm', duration: 0 },
      { src: './images/reels/reel.webp', duration: 4500 },
      { src: './images/reels/reel.webp', duration: 3500 },
    ],
  },
  {
    id: 'reel-8',
    title: 'Димсам и закуски',
    subtitle: 'Идеально к вечерним встречам',
    text: 'Подача, которую хочется снять в сторис',
    avatar: '/images/reels/reel.webp',
    preview: './images/reels/reel.webp',
    items: [
      { src: './images/reels/reel.webp', duration: 4500 },
      { src: './files/reels.webm', duration: 0 },
      { src: './images/reels/reel.webp', duration: 4500 },
      { src: './images/reels/reel.webp', duration: 3500 },
    ],
  },
  {
    id: 'reel-9',
    title: 'Димсам и закуски',
    subtitle: 'Идеально к вечерним встречам',
    text: 'Подача, которую хочется снять в сторис',
    avatar: '/images/reels/reel.webp',
    preview: './images/reels/reel.webp',
    items: [
      { src: './images/reels/reel.webp', duration: 4500 },
      { src: './files/reels.webm', duration: 0 },
      { src: './images/reels/reel.webp', duration: 4500 },
      { src: './images/reels/reel.webp', duration: 3500 },
    ],
  },
];
